name: Compile, Test, and Build Docs
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        ghc-ver: ["9.0.1"]
        cabal-ver: ["3.4.0.0"]

    steps:

    - name: Checkout repo
      uses: actions/checkout@v2.3.4

# Install GHC & Cabal
    - uses: actions/cache@v2
      name: Cache cabal packages
      id: cache-cabal
      with:
        path: |
          ~/.cabal/packages
          ~/.cabal/store
          ~/.cabal/bin
          dist
          dist-newstyle
        key: ${{ runner.os }}-${{ matrix.ghc-ver }}-${{ matrix.cabal-ver }}-${{ hashFiles('monus-weighted-search.cabal') }}-${{ hashFiles('**') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.ghc-ver }}-${{ matrix.cabal-ver }}-${{ hashFiles('monus-weighted-search.cabal') }}-
          ${{ runner.os }}-${{ matrix.ghc-ver }}-${{ matrix.cabal-ver }}-

    - name: Install ghc and cabal
      uses: haskell/actions/setup@v1.2.2
      with:
        ghc-version: ${{ matrix.ghc-ver }}
        cabal-version: ${{ matrix.cabal-ver }}

    - name: Put cabal programs in PATH
      run: echo "~/.cabal/bin" >> $GITHUB_PATH

    - name: Install cabal-docspec
      run: |
        mkdir -p $HOME/.cabal/bin
        curl -sL https://github.com/phadej/cabal-extras/releases/download/cabal-docspec-0.0.0.20210111/cabal-docspec-0.0.0.20210111.xz > cabal-docspec.xz
        echo '0829bd034fba901cbcfe491d98ed8b28fd54f9cb5c91fa8e1ac62dc4413c9562  cabal-docspec.xz' | sha256sum -c -
        xz -d < cabal-docspec.xz > $HOME/.cabal/bin/cabal-docspec
        rm -f cabal-docspec.xz
        chmod a+x $HOME/.cabal/bin/cabal-docspec
        cabal-docspec --version

# Compile Local Haskell
    - name: Build and Test Haskell
      run: |
        cabal build
        cabal test
        cabal -v new-haddock --haddock-hyperlink-source --haddock-html-location='https://hackage.haskell.org/package/$pkg-$version/docs' --enable-documentation
        cabal-docspec --check-properties --property-variables n

# Deploy Haskell docs to site
    - name: Deploy haddocks to github pages
      uses: peaceiris/actions-gh-pages@v3.7.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: dist-newstyle/build/x86_64-linux/ghc-${{ matrix.ghc-ver }}/monus-weighted-search-0.1.0.0/opt/doc/html/monus-weighted-search
